apiVersion: v1
kind: Service
metadata:
  name: loans-app-web-svc
  labels:
    app: loans-app-web
spec:
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: loans-app-web
  type: NodePort 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: loans-app-web-dep
  labels:
    app: loans-app-web
spec:
  selector:
    matchLabels:
      app: loans-app-web
      tier: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: loans-app-web
        tier: web
    spec:
      containers:
      - image: stackaero/mortgage-ui:latest
        name: loans-app-web
        imagePullPolicy: Always
        env:
          - name: API_HOST
            value: "loans-api.gke.stacklynx.com" 
          - name: API_PORT
            value: "443" 
          - name: API_URI_SCHEME
            value: "https"                                                             
        ports:
        - containerPort: 8080
          name: loans-web
 