apiVersion: v1
kind: Service
metadata:
  name: loans-app-api-svc
  labels:
    app: loans-app-api
spec:
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: loans-app-api
  type: NodePort 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: loans-app-api-dep
  labels:
    app: loans-app-api
spec:
  selector:
    matchLabels:
      app: loans-app-api
      tier: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: loans-app-api
        tier: web
    spec:
      containers:
      - image: stackaero/mortgage-api:latest
        name: loans-app-api
        imagePullPolicy: Always
        env:
          - name: DB_USER
            value: "appuser"
          - name: DB_NAME
            value: "mortgage_loan_db"
          - name: DB_HOST
            value: "loans-db-svc"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: loan-app-secrets
                key: MYSQL_PASSWORD                                                          
        ports:
        - containerPort: 8080
          name: loans-api
 